"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { AppShell } from "@mantine/core";

import EmotionProvider from "./components/Providers/emotion";

import Navigation from "./components/layout/Navigation";
import Header from "./components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <EmotionProvider>
          <AppShell navbar={<Navigation />} header={<Header />}>
            {children}
          </AppShell>
        </EmotionProvider>
      </body>
    </html>
  );
}
